# ~/.config/starship.toml

add_newline = false

[line_break]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
truncation_symbol = "../"
truncate_to_repo = false
format = 'ó°˜ [$path]($style)[$read_only]($read_only_style) '
read_only = " ğŸ”’"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[â†’](#3DCF6D) "
error_symbol = "[â†’](#C04742) "

# Git
[git_branch]
format = 'git:\($branch(:$remote_branch)\)($style) '

[git_status]
ahead = " ï²${count} "
behind = " ï´${count} "
staged = " î¯“${count} "
modified = " ï‘„${count} "
untracked = " ïƒ¢${count} "
deleted = " ó°—¨${count}"

[package]
disabled = true

[lua]
disabled = false

[nodejs]
format = 'via [node $version](bold green) '
